project:
  type: website
  output-dir: docs

website:
  title: "RCOs Data Reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data_sources.qmd

format:
  html:
    theme: 
      - mystyles.scss
    css: styles.css
    toc: true

editor: visual

